//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostBinary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostBinary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bStart {
            get {
                object obj = ResourceManager.GetObject("bStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bStartGray {
            get {
                object obj = ResourceManager.GetObject("bStartGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syntax Error.
        /// </summary>
        internal static string validErEn0 {
            get {
                return ResourceManager.GetString("validErEn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing {0} bracket in expression.
        /// </summary>
        internal static string validErEn1 {
            get {
                return ResourceManager.GetString("validErEn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No such operation.
        /// </summary>
        internal static string validErEn2 {
            get {
                return ResourceManager.GetString("validErEn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variable or number missing.
        /// </summary>
        internal static string validErEn3 {
            get {
                return ResourceManager.GetString("validErEn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect scientific notation.
        /// </summary>
        internal static string validErEn4 {
            get {
                return ResourceManager.GetString("validErEn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing &apos;-&apos; or &apos;+&apos; in expression.
        /// </summary>
        internal static string validErEn5 {
            get {
                return ResourceManager.GetString("validErEn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only digits allowed to represent array index.
        /// </summary>
        internal static string validErEn6 {
            get {
                return ResourceManager.GetString("validErEn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only integers allowed to represent array index.
        /// </summary>
        internal static string validErEn7 {
            get {
                return ResourceManager.GetString("validErEn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Missing array identifier.
        /// </summary>
        internal static string validErEn8 {
            get {
                return ResourceManager.GetString("validErEn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Only positive integers should represent array index.
        /// </summary>
        internal static string validErEn9 {
            get {
                return ResourceManager.GetString("validErEn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Синтаксическая ошибка в выражении.
        /// </summary>
        internal static string validErRu0 {
            get {
                return ResourceManager.GetString("validErRu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не хватает скобки {0} в выражении.
        /// </summary>
        internal static string validErRu1 {
            get {
                return ResourceManager.GetString("validErRu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Такой операции не существует.
        /// </summary>
        internal static string validErRu2 {
            get {
                return ResourceManager.GetString("validErRu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует переменная или число.
        /// </summary>
        internal static string validErRu3 {
            get {
                return ResourceManager.GetString("validErRu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка в научной нотации.
        /// </summary>
        internal static string validErRu4 {
            get {
                return ResourceManager.GetString("validErRu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не хватает знака &apos;-&apos; или &apos;+&apos; в выражении.
        /// </summary>
        internal static string validErRu5 {
            get {
                return ResourceManager.GetString("validErRu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu6 {
            get {
                return ResourceManager.GetString("validErRu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только целые числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu7 {
            get {
                return ResourceManager.GetString("validErRu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя переменной отсутствует.
        /// </summary>
        internal static string validErRu8 {
            get {
                return ResourceManager.GetString("validErRu8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только положительные числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu9 {
            get {
                return ResourceManager.GetString("validErRu9", resourceCulture);
            }
        }
    }
}
