//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostBinary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostBinary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bStart {
            get {
                object obj = ResourceManager.GetObject("bStart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bStartGray {
            get {
                object obj = ResourceManager.GetObject("bStartGray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error.
        /// </summary>
        internal static string validErEn0 {
            get {
                return ResourceManager.GetString("validErEn0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing {0} bracket in expression.
        /// </summary>
        internal static string validErEn1 {
            get {
                return ResourceManager.GetString("validErEn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect constant.
        /// </summary>
        internal static string validErEn10 {
            get {
                return ResourceManager.GetString("validErEn10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such operation.
        /// </summary>
        internal static string validErEn2 {
            get {
                return ResourceManager.GetString("validErEn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable or number missing.
        /// </summary>
        internal static string validErEn3 {
            get {
                return ResourceManager.GetString("validErEn3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect scientific notation.
        /// </summary>
        internal static string validErEn4 {
            get {
                return ResourceManager.GetString("validErEn4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;-&apos; or &apos;+&apos; in expression.
        /// </summary>
        internal static string validErEn5 {
            get {
                return ResourceManager.GetString("validErEn5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only digits allowed to represent array index.
        /// </summary>
        internal static string validErEn6 {
            get {
                return ResourceManager.GetString("validErEn6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only integers allowed to represent array index.
        /// </summary>
        internal static string validErEn7 {
            get {
                return ResourceManager.GetString("validErEn7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing array identifier.
        /// </summary>
        internal static string validErEn8 {
            get {
                return ResourceManager.GetString("validErEn8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for variables you can not put a sign &apos;*&apos;.
        /// </summary>
        internal static string validErEn9 {
            get {
                return ResourceManager.GetString("validErEn9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Синтаксическая ошибка в выражении.
        /// </summary>
        internal static string validErRu0 {
            get {
                return ResourceManager.GetString("validErRu0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не хватает скобки {0} в выражении.
        /// </summary>
        internal static string validErRu1 {
            get {
                return ResourceManager.GetString("validErRu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой операции не существует.
        /// </summary>
        internal static string validErRu2 {
            get {
                return ResourceManager.GetString("validErRu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует переменная или число.
        /// </summary>
        internal static string validErRu3 {
            get {
                return ResourceManager.GetString("validErRu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в научной нотации.
        /// </summary>
        internal static string validErRu4 {
            get {
                return ResourceManager.GetString("validErRu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не хватает знака &apos;-&apos; или &apos;+&apos; в выражении.
        /// </summary>
        internal static string validErRu5 {
            get {
                return ResourceManager.GetString("validErRu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu6 {
            get {
                return ResourceManager.GetString("validErRu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только целые числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu7 {
            get {
                return ResourceManager.GetString("validErRu7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя переменной отсутствует.
        /// </summary>
        internal static string validErRu8 {
            get {
                return ResourceManager.GetString("validErRu8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только положительные числа допустимы в качестве индекса.
        /// </summary>
        internal static string validErRu9 {
            get {
                return ResourceManager.GetString("validErRu9", resourceCulture);
            }
        }
    }
}
